name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        shell: pwsh
        run: |
          npm install -g yarn
          yarn --version

      - name: Build App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${GITHUB_REF_NAME}
          releaseName: "Hermes v${GITHUB_REF_NAME}"
          releaseBody: "Automatic release of Hermes v${GITHUB_REF_NAME}"
